openapi: 3.0.1
info:
  title: API DOCUMENTATION
  description: API Documentation for Challenge 6 about Post and Deploy
  version: 1.0.1
  contact:
    email: adewanggan@gmail.com
servers:
  - url: http://localhost:3000/api/v1
  - url: https://binar-project-backend.vercel.app/api/v1
tags:
  - name: Auth
    description: Everything about your Authentication
paths:
  /auth/register:
    post:
      tags:
        - "Users"
      summary: Register
      description: Mendaftarkan account baru kedalam database untuk sebuah akses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: dewangga
                email:
                  type: string
                  example: dewangga@gmail.com
                password:
                  type: string
                  example: "12345"

      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Successfully created account
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            example: a9bc30c4-9408-454b-8815-92ee6cbf46d7
                          name:
                            type: string
                            example: dewangga
                          email:
                            type: string
                            example: dewangga@gmail.com
                          is_verified:
                            type: boolean
                            example: false
                          role:
                            type: string
                            example: USER
                          createdAt:
                            type: string
                            format: datetime
                            example: "2024-05-22T04:05:11.993Z"
                          updatedAt:
                            type: string
                            format: datetime
                            example: "2024-05-22T04:05:11.993Z"

        409:
          description: Email has already been used!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Email already used
                  data:
                    example: ~

        400:
          description: Input must be required
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Missing required field
                  data:
                    example: ~

  /auth/login:
    post:
      tags:
        - "Users"
      summary: Login
      description: Login account untuk meminta token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: dewangga
                email:
                  type: string
                  example: dewangga@gmail.com
                password:
                  type: string
                  example: "12345"

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User logged in success
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            example: a9bc30c4-9408-454b-8815-92ee6cbf46d7
                          

        400:
          description: Input must be required
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Missing required field
                  data:
                    example: ~

        401:
          description: Incorrect password
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid password.
                  data:
                    example: ~

        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Account not found.
                  data:
                    example: ~
