openapi: 3.0.1
info:
  title: NGEFLY.COM
  description: API Documentation for NGEFLY.COM
  version: 1.0.1
  contact:
    email: adewanggan@gmail.com
servers:
  - url: http://localhost:3000/api/v1
  - url: https://binar-project-backend.vercel.app/api/v1
tags:
  - name: Auth
    description: Everything about your Authentication
paths:
  /auth/register:
    post:
      tags:
        - "Auth"
      summary: Register
      description: Register a new account into the database for access
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: dewangga
                email:
                  type: string
                  example: dewangga@gmail.com
                password:
                  type: string
                  example: "12345"

      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Successfully created account
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            example: a9bc30c4-9408-454b-8815-92ee6cbf46d7
                          name:
                            type: string
                            example: dewangga
                          email:
                            type: string
                            example: dewangga@gmail.com
                          is_verified:
                            type: boolean
                            example: false
                          role:
                            type: string
                            example: USER
                          createdAt:
                            type: string
                            format: datetime
                            example: "2024-05-22T04:05:11.993Z"
                          updatedAt:
                            type: string
                            format: datetime
                            example: "2024-05-22T04:05:11.993Z"

        409:
          description: Email has already been used!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Email already used
                  data:
                    example: ~

        400:
          description: Input must be required
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Missing required field
                  data:
                    example: ~
  /auth/verify/send:
    post:
      tags:
        - "Auth"
      summary: Verify Send
      description: Send an Email to Verify
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: dumpfile978@gmail.com
        
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Mail sent. Please check your email
                  data:
                    example: ~

        404:
          description: Account not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Account not found.
                  data:
                    example: ~

        409:
          description: Account already verified.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Account already verified.
                  data:
                    example: ~


  /auth/login:
    post:
      tags:
        - "Auth"
      summary: Login
      description: Login account to request a token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: dewangga@gmail.com
                password:
                  type: string
                  example: "12345"

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User logged in success
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 5a33647a-4f3d-4287-aba1-650b92a7a253
                      name:
                        type: string
                        example: Admin
                      email:
                        type: string
                        example: admin@admin.com
                      is_verified:
                        type: boolean
                        example: true
                      role:
                        type: string
                        example: ADMIN
                      createdAt:
                        type: string
                        format: datetime
                        example: "2024-05-22T04:03:20.510Z"
                      updatedAt:
                        type: string
                        format: datetime
                        example: "2024-05-22T04:03:20.510Z"
                      token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhMzM2NDdhLTRmM2QtNDI4Ny1hYmExLTY1MGI5MmE3YTI1MyIsIm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiaXNfdmVyaWZpZWQiOnRydWUsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMjQtMDUtMjJUMDQ6MDM6MjAuNTEwWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDUtMjJUMDQ6MDM6MjAuNTEwWiIsImlhdCI6MTcxNjM1NzMxMH0.DX5JBe_qs5gD2jwzcSUAOEdpYxal0PZafYIhFEeV5Uc
                          

        400:
          description: Input must be required
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    anyOf:
                      - type: string
                        example: Missing required field
                      - type: string
                        example: Invalid password.
                  data:
                    example: ~

        401:
          description: Account is not verified yet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Account is not verified yet.
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            example: a9bc30c4-9408-454b-8815-92ee6cbf46d7
                          name:
                            type: string
                            example: dewangga
                          email:
                            type: string
                            example: dewangga@gmail.com
                          is_verified:
                            type: boolean
                            example: false
                          role:
                            type: string
                            example: USER
                          createdAt:
                            type: string
                            format: datetime
                            example: "2024-05-22T04:05:11.993Z"
                          updatedAt:
                            type: string
                            format: datetime
                            example: "2024-05-22T04:05:11.993Z"

        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Account not found.
                  data:
                    example: ~
